name: Tests

on: pull_request

jobs:

  shellcheck:
    runs-on: ubuntu-18.04
    container: docker://koalaman/shellcheck-alpine
    steps:
    - uses: actions/checkout@v2
    - run: shellcheck utilities/*

  tests:
    runs-on: ubuntu-18.04

    env:
      DATABASE_URL: postgres://postgres@localhost:5432/postgres
      RABBITMQ_URL: amqp://guest:guest@localhost:5672/

    services:

      postgres:
        image: postgres:11-alpine
        env:
          POSTGRES_HOST_AUTH_METHOD: trust
        ports:
        - 5432:5432

      rabbitmq:
        image: rabbitmq:3-management-alpine
        ports:
        - 5672:5672
        - 15672:15672

    steps:
    - uses: actions/checkout@v2

    - run: |
        mkdir -p ~/cache ~/bin
        sudo apt-get -yqq update
        sudo apt-get -yqq install --no-install-recommends libpq-dev postgresql-client

    - run: test/test.bash
